/**
 * @signvoy/react — Official Signvoy React SDK
 *
 * This entrypoint is hand-authored. The generated/ directory contains the raw
 * typescript-fetch OpenAPI client (regenerated by CI when the API spec
 * changes); this package layers a browser-safe React surface on top of it:
 *
 *   - <SignvoyEmbed />   embedded signing iframe with lifecycle callbacks
 *   - useSignvoyEmbed()  headless controller for custom iframe rendering
 *   - <SignvoyProvider>  optional shared configuration
 *
 * Keep your secret API key on the server: mint embed-session URLs with
 * @signvoy/node, then pass the returned `url` into <SignvoyEmbed />.
 */

export { SignvoyEmbed } from "./embed";
export type { SignvoyEmbedProps } from "./embed";

export { useSignvoyEmbed } from "./useSignvoyEmbed";
export type {
  SignvoyEmbedStatus,
  SignvoyEmbedHandlers,
  UseSignvoyEmbedOptions,
  UseSignvoyEmbedResult,
} from "./useSignvoyEmbed";

export { SignvoyProvider, useSignvoyConfig } from "./provider";
export type { SignvoyProviderProps, SignvoyConfig } from "./provider";

export { parseEmbedEvent } from "./events";
export type {
  SignvoyEmbedEvent,
  SignvoyEmbedEventType,
  SignvoyReadyEvent,
  SignvoyCompletedEvent,
  SignvoyDeclinedEvent,
  SignvoyEmbedErrorEvent,
} from "./events";
